name: Deploy MkDocs to GitHub Pages
on:
  push:
    branches:
      - main  # Adjust if your default branch is named differently
permissions:
  contents: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and Material theme
        run: |
          pip install mkdocs mkdocs-material
          
      - name: Install MkDocs Plugin
        run: |
          pip install mkdocs-include-markdown-plugin

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
